#include "FormationControlV2/SlotLocalPathPrimitiveV2.h"
#include <cmath>
#include <iostream>
#include <limits>
using namespace FormationControlV2;
namespace {int F{},C{};void Check(bool x,const char*n){++C;if(!x){++F;std::cerr<<"FAIL "<<n<<'\n';}}
SlotLocalPathInputV2 Base(){SlotLocalPathInputV2 i{};i.SlotPose={{0,0},0};i.bSlotCurvatureValid=true;i.FollowerTurnRadiusBoundM=50;i.Generation=7;i.SimulationTimeS=12;return i;}}
int main(){auto i=Base();i.FollowerPositionNE={20,10};auto s=SlotLocalPathPrimitiveV2::Project(i);Check(s.bValid&&s.Kind==SlotLocalPathKindV2::Straight,"straight_valid");Check(std::abs(s.Path.Position.N-20)<1e-12&&std::abs(s.Path.Position.E)<1e-12,"straight_projection");Check(std::abs(s.SignedCrossTrackErrorM-10)<1e-12,"straight_cross_right_positive");Check(std::abs(s.Path.UnitTangent.N-1)<1e-12,"straight_tangent");
 i=Base();i.SlotCurvaturePerM=.01;i.FollowerPositionNE={100,30};auto r=SlotLocalPathPrimitiveV2::Project(i);Check(r.bValid&&r.Kind==SlotLocalPathKindV2::ConstantCurvatureCircle,"right_circle");Check(std::abs(r.CircleCenterNE.E-100)<1e-12&&std::abs(r.CircleRadiusM-100)<1e-12,"right_center_radius");Check(std::abs(r.Path.UnitTangent.Norm()-1)<1e-12&&std::abs(r.Path.SignedCurvaturePerM-.01)<1e-15,"right_tangent_curvature");
 i.SlotCurvaturePerM=-.01;i.FollowerPositionNE={100,-30};auto l=SlotLocalPathPrimitiveV2::Project(i);Check(l.bValid&&std::abs(l.CircleCenterNE.E+100)<1e-12,"left_center");Check(std::abs(l.SignedCrossTrackErrorM+r.SignedCrossTrackErrorM)<1e-9,"left_right_symmetry");
 i=Base();i.SlotCurvaturePerM=.01;i.FollowerPositionNE={0,0};auto on=SlotLocalPathPrimitiveV2::Project(i);Check(on.bValid&&on.ProjectionDistanceM<1e-12,"exact_on_path");i.FollowerPositionNE={0,100};Check(SlotLocalPathPrimitiveV2::Project(i).Failure==SlotLocalPathFailureV2::NearCircleCenter,"near_center_invalid");
 i=Base();i.bSlotCurvatureValid=false;i.bAllowStraightAssumption=false;Check(SlotLocalPathPrimitiveV2::Project(i).Failure==SlotLocalPathFailureV2::CurvatureUnavailable,"curvature_unavailable");i.bAllowStraightAssumption=true;Check(SlotLocalPathPrimitiveV2::Project(i).bStraightAssumed,"explicit_straight_assumption");
 i=Base();i.SlotCurvaturePerM=.02;i.FollowerTurnRadiusBoundM=100;Check(SlotLocalPathPrimitiveV2::Project(i).Failure==SlotLocalPathFailureV2::CurvatureInfeasible,"curvature_infeasible_no_clamp");
 i=Base();i.FollowerPositionNE={std::numeric_limits<double>::quiet_NaN(),0};Check(!SlotLocalPathPrimitiveV2::Project(i).bValid,"nan_invalid");
 i=Base();i.FollowerPositionNE={12,3};auto meta=SlotLocalPathPrimitiveV2::Project(i);Check(meta.Generation==7&&meta.TimestampS==12,"generation_timestamp");
 NearFieldSpeedInputV2 n{};n.SlotGroundVelocityNE={100,0};n.SlotUnitTangentNE={1,0};n.FollowerGroundVelocityNE={100,0};n.WindVelocityNE={};n.EasToTasRatio=1;n.DtS=1;n.bWindValid=n.bRatioValid=n.bEnvelopeValid=true;n.AlongErrorM=-200;auto behind=NearFieldSpeedPlannerV2::Compute(n);Check(behind.bValid&&behind.ClosureDeltaMps>0&&behind.TargetGroundSpeedMps>100,"behind_accelerates");n.AlongErrorM=200;auto ahead=NearFieldSpeedPlannerV2::Compute(n);Check(ahead.bValid&&ahead.ClosureDeltaMps<0&&ahead.TargetGroundSpeedMps<100,"ahead_decelerates");n.AlongErrorM=0;auto hold=NearFieldSpeedPlannerV2::Compute(n);Check(hold.bValid&&std::abs(hold.TargetGroundSpeedMps-100)<1e-12,"hold_matches_slot");n.bWindValid=false;Check(NearFieldSpeedPlannerV2::Compute(n).Failure==NearFieldSpeedFailureV2::InvalidWind,"invalid_wind_no_fallback");n.bWindValid=true;n.bRatioValid=false;Check(NearFieldSpeedPlannerV2::Compute(n).Failure==NearFieldSpeedFailureV2::InvalidRatio,"invalid_ratio");
 std::cout<<"SLOT_LOCAL_PATH_V2 checks="<<C<<" failures="<<F<<'\n';return F?1:0;}
